---
- name: check for supported OS
  assert:
    that:
      - "ansible_os_family in supported_ansible_os_families"

- name: check for supported server implementation
  assert:
    that:
      - "minecraft_server in supported_minecraft_servers"

- name: Open minecraft port
  ufw:
    rule: allow
    port: 25565

- include: "{{ minecraft_hook_before_setup | default('empty.yml') }}"

- include: setup/main.yml

- include: "{{ minecraft_hook_after_setup | default('empty.yml') }}"

- include: "{{ minecraft_hook_before_download | default('empty.yml') }}"

- include: download/main.yml

- include: "{{ minecraft_hook_after_download | default('empty.yml') }}"

- include: "{{ minecraft_hook_before_install | default('empty.yml') }}"

- include: install/main.yml

- include: "{{ minecraft_hook_after_install | default('empty.yml') }}"

- include: acl.yml

- include: configure.yml

- include: "{{ minecraft_hook_before_start | default('empty.yml') }}"

- meta: flush_handlers

- include: "{{ minecraft_hook_after_start | default('empty.yml') }}"
